name: 'OpenResty OPM Publish'
description: 'Publish a package to OpenResty's OPM package manager.'
inputs:
  github-account:
    description: 'Github user or organization to use for uploading package.'
    required: true
  github-token:
    description: 'Github personal access token used for package uploads.'
    required: true
  upload-server:
    description: 'OPM server for uploading packages.'
    default: 'https://opm.openresty.org'
  download-server:
    description: 'OPM server for downloading packages.'
    default: 'https://opm.openresty.org'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-account }}
    - ${{ inputs.github-token }}
    - ${{ inputs.upload-server }}
    - ${{ inputs.download-server }}